# NumPy packeage

In [4]:
# load Numpy package
import numpy as np

In [3]:
#create two - dimensional array
myArray = np.array([[10,20,30], [210, 220, 230]])

In [5]:
# Displays the array

myArray

array([[ 10,  20,  30],
       [210, 220, 230]])

In [7]:
# Display the shape
myArray.shape

(2, 3)

In [8]:
# Display the size
myArray.size

6

## Notes

# Array Functions

In [11]:
# create  array
array1 = np.array([['a','a'],['b', 'b'], ['c' ,'c']])

In [21]:
# insert 'z's in row 3
np.insert(array1, 3, 'z', axis=0)

array([['a', 'a'],
       ['b', 'b'],
       ['c', 'c'],
       ['z', 'z']], dtype='<U1')

In [23]:
# insert 0s in colums 1
np.insert(array1, 1, '0', axis=1)

array([['a', '0', 'a'],
       ['b', '0', 'b'],
       ['c', '0', 'c']], dtype='<U1')

In [25]:
# delete row 1
np.delete(array1, 1, axis=0)

array([['a', 'a'],
       ['c', 'c']], dtype='<U1')

In [26]:
np.zeros(3)

array([0., 0., 0.])

In [27]:
# Create another array2
array2 = np.array(['z','b', 'a', 'd', 'c'])

In [28]:
# Display the other array
array2

array(['z', 'b', 'a', 'd', 'c'], dtype='<U1')

In [29]:
# sort array2
np.sort(array2, None)

array(['a', 'b', 'c', 'd', 'z'], dtype='<U1')

In [31]:
# Delete array element with index 1

np.delete(array2,1)

array(['z', 'a', 'd', 'c'], dtype='<U1')

In [34]:
array3 = np.array([[3, 2], [5, 6], [4, 2]])
array3

array([[3, 2],
       [5, 6],
       [4, 2]])

In [36]:
# sort along axis=0 which is the row

np.sort(array3, axis=0)

array([[3, 2],
       [4, 2],
       [5, 6]])

In [37]:
# sort along axis=1 which is the column
np.sort(array3, axis=1)

array([[2, 3],
       [5, 6],
       [2, 4]])

# Notes

# Shape functions



In [38]:
array1 = np.array([[1,2],[3,4]])
array1

array([[1, 2],
       [3, 4]])

In [46]:
# Return a flattened array
np.reshape(array1, (1,4)) # one row with 4 columns

array([[1, 2, 3, 4]])

In [47]:
# create another array
array2 = np.array([[1,2],[3,4], [5,6]])
array2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
# Return a flattened array
np.ravel(array2)

array([1, 2, 3, 4, 5, 6])

In [49]:
# Resize array to a 2 by 3 array
np.resize(array2, (2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
# Transpose the array

np.transpose(array2)

array([[1, 3, 5],
       [2, 4, 6]])

# Math operators and funtions

In [52]:
# create array1
array1 = np.array([[1,2],[3,4]])
array1

array([[1, 2],
       [3, 4]])

In [53]:
# create another array2
array2 = np.array([[5,6],[7,8]])
array2

array([[5, 6],
       [7, 8]])

In [54]:
# Add array1 and array2
array1 + array2

array([[ 6,  8],
       [10, 12]])

In [55]:
# Substract array1 - array2
array1 - array2


array([[-4, -4],
       [-4, -4]])

In [57]:
# multiply array1 and array2
array1 * array2

array([[ 5, 12],
       [21, 32]])

In [58]:
# Divide array / array
array1 / array2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [59]:
# find square root of array 2 elements
np.sqrt(array2)

array([[2.23606798, 2.44948974],
       [2.64575131, 2.82842712]])

In [61]:
# find log of array 1 elements
np.log(array1)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [63]:
# find the dot product of the two arrays
np.dot(array1, array2)

array([[19, 22],
       [43, 50]])

In [64]:
# find the max element
np.max(array1)

4

In [65]:
# Find the median
np.median(array2)

6.5

In [67]:
# find std
np.std(array1)

1.118033988749895

In [68]:
# Matrix funtions
np.matmul(array1, array2)



array([[19, 22],
       [43, 50]])